runtime: micro-nginx

fullnameOverride: micro-nginx

deployment:
  replicas: 1
  image:
    pullPolicy: IfNotPresent
    repository: nginx
    tag: stable-otel
  readinessProbe:
    enabled: false
  livenessProbe:
    enabled: false
  ports:
    - name: http
      containerPort: 8080
      protocol: TCP

service:
  ports:
    - name: http-8080
      port: 8080
      protocol: TCP
      targetPort: 8080-tcp

hpa:
  enabled: false